services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: chatdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./router/ddl:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  router:
    build: ./router
    env_file:
      - ./router/.env      # PGHOST=db, PGUSER=postgres, PGPASSWORD=12345, PGDATABASE=chatdb, PGPORT=5432, PORT=5000
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      PGHOST: db
      PGPORT: "5432"
      PGDATABASE: chatdb
      PGUSER: postgres
      PGPASSWORD: 12345
      PORT: "5000"
      
  ws-server:
    build: ./WebSocketServer
    environment:
      DB_ADDR: postgresql://postgres:12345@db:5432/chatdb
      MASTER_URL: ""
      HOST: "0.0.0.0"
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client
    depends_on:
      - router
    ports:
      - "3000:80"

volumes:
  postgres-data: